[package]
name = "me"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
pulldown-cmark = "0.12.0"
shuttle-axum = "0.47.0"
shuttle-runtime = "0.47.0"
tokio = "1.40.0"
tower-livereload = "0.9.3"
walkdir = "2.5.0"